name: New rails app

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  pull-requests: write
  
jobs:
  new-rails-app:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: fals
          fetch-depth: 0
          
      - name: Set up Node.js
        uses: actions/setup-node@v3

      - run: |
          cd artifact.zip
          mkdir artifact
          unzip artifact.zip -d artifact

      - name: Commit & Push changes
        uses: actions-js/push@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_email: '185859974+oc-2@users.noreply.github.com'
          author_name: 'oc-2'
          message: 'config new rails app'
          branch: 'main'