name: New rails app

on:
  push:
    branches:
      - main

jobs:
  new-rails-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12.13.0
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Install Npm
        run: npm install -g npm@12.13.0
      - name: Install Yarn
        run: npm i -g yarn@1.22.5   
      - name: Install bundler and rails
        run: gem install rails -v 6.0.3.3
      - name: Create new rails app
        run: rails new test-jekyll
      - name: Commit and Push
        run: |
          git config --global user.name "oc-2"
          git config --global user.email "185859974+oc-2@users.noreply.github.com"
          git add .
          git commit -m "Create github action for new rails app" --allow-empty
          git push origin HEAD:main
